language: python
sudo: yes
python:
#- '3.4'
#- '3.5'
- '3.6'

env:
- SALTVERSION=stable 2015.8
- SALTVERSION=stable 2016.3
- SALTVERSION=stable 2016.11
- SALTVERSION=stable 2017.7
- SALTVERSION=git

before_install:
  - sudo apt-get update
  # Install salt minion for local use
  - curl -L http://bootstrap.saltstack.org | sudo sh -s -- -M -X $SALTVERSION
  # Set up our installation bits
  - sudo mkdir -p /srv/salt/states
  # TODO: Adjust these paths to match your project.
  - sudo cp minion.bootstrap /etc/salt/minion
  - sudo cp -r states/* /srv/salt/states

install:
  # Stand up the instance
  - sudo salt-call --local --retcode-passthrough state.highstate
  # Give salt time to wake up
  - sleep 5

script:
  # TODO: Fill in your actual test suite
  - sudo salt-run salt.cmd test.versions_report
  - sudo salt '*' test.versions_report
