language: python
sudo: yes
python:
#- '3.4'
#- '3.5'
- '3.6'

env:
- SALTVERSION=stable 2016.11
- SALTVERSION=stable 2017.7
- SALTVERSION=git

before_install:
  - sudo apt-get update
  # Install salt minion for local use
  - curl -L http://bootstrap.saltstack.org | sudo sh -s -- -M -X $SALTVERSION
  # Set up our installation bits
  - sudo cp minion.bootstrap /etc/salt/minion
  - sudo mkdir -p /srv/salt/states
  - sudo cp -r states/* /srv/salt/states

install:
  - sudo find /etc/salt
  - sudo find /srv/salt/states
  # Stand up the instance
  - sudo salt-call --local --retcode-passthrough saltutil.wheel key.gen_keys keyname=lively
  - sudo salt-call --local --retcode-passthrough state.highstate
  # Give salt-minion time to generate keys
  - sleep 5
  - sudo salt-key -L
  - ps aux|cat -
  - sudo cat /var/log/salt/minion
  - sudo salt-key -a lively

  # If anything bad happened on restarting the minion,
  # we'll want to see the logs
  #- sudo cat /var/log/salt/*

  # For additional debugging, see what's in grains on a travis box
  # - sudo salt '*' grains.items

script:
  # TODO: Fill in your actual test suite
  - sudo salt-run salt.cmd test.versions_report
  - sudo salt '*' test.versions_report
